### ISSUE TITLE
Notes (October 6-October 27)

### ISSUE THREAD

**Issue by duckinator** [duckinator/STAYFOCUSED#10]
I've spent this week using Stayfocused to work through my ideas for Stayfocused, and am very much looking forward to resolving the handful of outstanding questions and implementing all of my ideas.

# Design

The current implementation is a very good starting point, but I realized I needed to determine the functionality I want, refine the design a bit, and figure out what questions are still unanswered.

## Functionality

- [ ] tasks can be marked as done
- [ ] tasks can be persistent
- [ ] persistent tasks *can not* be manually marked as done, but are *indicated* as done if the time commitments has been met
- [ ] tasks can have tags
- [ ] tasks can have a time commitment (per day or per week)
- [ ] tasks can have sub-tasks
- [ ] tasks store the time they have been worked on for a given day
- [ ] tasks retain tracked time for previous days
- [ ] each tag can have an associated template, to export a report of all tasks with that tag

## Tags

- [ ] Figure out how tags should work.
  - Should they be a manually-edited list you add/remove things to?
  - Is a task associated with a list of tags, or is a tag associated with a list of tasks? (bidirectional relationship for this seems unnecessarily risky because they could get out of sync)

## Interface improvements

These can all be done right now.

Task view:
- [ ] more prominent indicator for whether it's tracking time or paused.
  - [ ] determine what this should look like (i want something nicer than just "make the button bigger")
- [ ] add an indicator specifying whether there's unsaved changes
- [ ] make note textarea fill all of the available space

Task view:
- [ ] keyboard shortcuts
- [ ] make textboxes fill available space
- [ ] move actions and elapsed time to the left side
  - there's *a literal foot* of dead space between the task and everything associated with it on my monitor

<details>
<summary>unorganized brain dump</summary>

- `#` indicates a header
- `[ ]` indicates a textbox
- `a | b | c` indicates different columns in a table
- `<x>` indicates a button
- time formatting is being treated very loosely for simplicity; the numbers used here are just hours, as a decimal

assuming it's a Monday, clicking <Copy schedule> then adding "Ruby Central" > "HackerOne Reports" and "Ruby Central" > "Review PRs" would result in

```
# Schedule
 Description        | Sun | Mon  | Tue  | Wed  | Thu  | Fri  | Sat | Total
[Fractal          ] | [ ] | [0 ] | [2 ] | [2 ] | [3 ] | [3 ] | [ ] | 10
[Ruby Central     ] | [ ] | [3 ] | [1 ] | [1 ] | [0 ] | [0 ] | [ ] | 5
# Tasks <Copy schedule>
Elapsed | Remaining | Description
[3]     | [3]       | [Ruby Central]
[0]     | [  ]      | `[HackerOne Reports]
[0]     | [  ]      |  [Review PRs]
```

</details>

<details>
<summary>screenshot of unedited notes</summary>

![image](https://github.com/user-attachments/assets/40c59669-7913-4b33-8185-cb5931a2621f)

</details>

**Comment by duckinator** [comment]
consolidated notes

![picture_2024-10-27_21-26-21-cropped](https://github.com/user-attachments/assets/2803d0a8-3897-4cb2-bba9-2a14247d715e)
